language: node_js
node_js:
  - "0.11"
  - "0.10"
script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo apt-get install -y libstdc++6
  - npm install tilestrata
  - make test
  - make test-ci-coverage || exit 0