language: cpp
os:
  - linux
env:
  matrix:
   - NODE_NVM_VERSION="0.11.14"
   - NODE_NVM_VERSION="0.10.33"
before_install:
  # upgrade libstdc++ to support C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo apt-get install -y libstdc++6
  # install node.js
  - git clone https://github.com/creationix/nvm.git ../.nvm
  - source ../.nvm/nvm.sh
  - nvm install $NODE_NVM_VERSION
  - nvm use $NODE_NVM_VERSION
  - node --version
  - npm --version
  - npm install tilestrata
script:
  # execute tests
  - make test
  - make test-ci-coverage || exit 0